name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ github.ref }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Compile
        run: npm run build
      - name: Rename
        run: mv dist/index.html dist/obs-stats.html
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.html
  draft_release:
    runs-on: ubuntu-latest
    needs: [build_binaries]
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: List Directory Files
        run: ls -laR
        shell: bash
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: obs-stats ${{ github.ref_name }}
          draft: true
          files: |
            *.html
